# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2c65f8bc077dcbe4def1855045d6c74a2285bbf547e4c9c5fd4eba7f41b2b57faa791549c1a3891d9de970c99ff512199e6eab694cb3c23291b76300b86ea5a

test:
  secret_key_base: 8441d817c72b5c69eb0ac4446de5ff3b7b9f20d75b712f38187400ae8988e10c3ef8a15af48f67066e3295171cc5f039eaa4b2c6f3f6af146bdfb0230d09d573

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
